   apiVersion: v1
   kind: Service
   metadata:
      labels:
        app: nagp
        branch: develop
      name: nagp-welcome-devops-svc-develop
      namespace: kubernetes-cluster-rabiamehta
   spec:
      selector:
        app: nagp
        branch: develop
      ports:
      -  name: nagp-svc-port-develop
         nodePort: 30158
         port: 8080
         targetPort: 8080
      type: NodePort