   apiVersion: v1
   kind: Service
   metadata:
      labels:
        app: nagp
      name: nagp-welcome-devops-svc-master
      namespace: kubernetes-cluster-rabiamehta
   spec:
      selector:
        app: nagp
        branch: master
      ports:
      -  name: nagp-svc-port-master
         nodePort: 30157
         port: 8080
         targetPort: 8080
      type: NodePort
   